FROM trufflesuite/ganache:latest as build

USER root

RUN apt update
RUN apt install -y make gcc g++ python git bash jq
RUN mkdir /iexec-poco
COPY . /iexec-poco
RUN mv /iexec-poco/config/config_native.json /iexec-poco/config/config.json

ARG MNEMONIC

RUN mkdir /ganachedb
RUN bash /iexec-poco/testchains/ganache/migrate.sh

FROM trufflesuite/ganache:latest as runtime

COPY --from=build "/ganachedb" "/ganachedb"

ENTRYPOINT ["node", "/app/dist/node/cli.js"]
CMD ["--miner.blockGasLimit", "8000000", "--chain.networkId", "65535", "--chain.chainId", "65535", "--chain.hardfork", "berlin", "--database.dbPath", "/ganachedb"]
