FROM openethereum/openethereum:v3.0.0

USER root

RUN apk update && apk add bash jq nodejs npm
RUN npm -v
RUN node -v

RUN mkdir /iexec-poco
COPY . /iexec-poco
RUN mv /iexec-poco/config/config_native.json /iexec-poco/config/config.json

ARG DEV_NODE
ARG MNEMONIC

RUN bash /iexec-poco/testchains/openethereum/1sec_no_seal/migrate.sh

ENTRYPOINT ["/home/openethereum/openethereum"]
CMD ["--chain", "/iexec-poco/testchains/openethereum/1sec_no_seal/spec.json", "--config", "/iexec-poco/testchains/openethereum/1sec_no_seal/authority.toml", "-d", "/iexec-poco/testchains/openethereum/1sec_no_seal/data", "--geth"]
