@startuml


:Uw:

:Dw:
cloud {
  [Ds]
}
component [Ds]
component [Dp]

:Sw:
cloud {
  [Ss]
}

component [Ss]
component [Sp]

:Ww:
component [Wp]

cloud {
  [POCOs]
}
component [POCOs]




Uw -down-> [Ds]
Dw -right-> [Ds]: owner
Dw -left-> Dp: control
Sw -up-> [Ss]: owner
Sw -down-> [Sp]: control

[Ds] <-down-> [POCOs]
[POCOs] <-down-> [Ss]
[Sp] <-up-> [Ss]
[Wp] <-up-> [Ss]

[Ww] -right-> [Wp]: control

[Wp] <-right-> [Sp]


[Wp] <-up-> [Dp]


'missing link :  [Dp] <-> [Wp] . add mannualy on img because i do not succeed to layout it



@enduml