@startuml


:Uw:

:Dw:
cloud {
  [Ds]
}
component [Ds]
component [Dp]

:Sw:
cloud {
  [Ss]
}

component [Ss]
component [Sp]

:Ww:
component [Wp]

cloud {
  [POCOs]
}
component [POCOs]




Uw -down-> [Ds]: 1) iexecSubmit()
Dw <-right- [Ds]:owned by
Dw -left-> Dp : control
Sw <-up- [Ss]:owned by
Sw -down-> [Sp]: control

[Ds] -down-> [POCOs]: 2a) submitTask()
[Ds] <-down- [POCOs]: 12) iexecSubmitCallback()
[POCOs] -down-> [Ss]:  2b) submitTask()
[POCOs] <-down- [Ss]:  11b) finalizedTask()
[Sp] <-up-> [Ss]: 3) acceptTask()\n4) callForContribution()\n7) revealConsensus\n11a) finalizedTask()
[Wp] <-up-> [Ss]: 6) contribute\n8) reveal

[Ww] -right-> [Wp] : control

[Wp] <-up-> [Dp]: 5) getApp()

[Wp] <-right-> [Sp]:10) getResult

'missing link :  [Dp] <-> [Wp] . add mannualy on img because i do not succeed to layout it



@enduml