@startuml
object DappAPI
object MyDapp
object DappHub {
  mapping (dapp address => Dapp Struct)
}
object WorkerPoolHub {
  address[] workerPools
  mapping (worker => worker pool) m_workerAffectation;
}

object Stake
object Scoring
object POCO
object WorkerPool {
   address[] workers
   mapping (taskID => Task) m_tasks;
   mapping (taskID => worker address => Work) m_tasksContributions;
}



DappHub <|-- POCO
WorkerPoolHub <|-- POCO
Stake <|-- POCO
Scoring <|-- POCO
WorkerPool "n" *-- "0" WorkerPoolHub

DappAPI <|-- MyDapp
MyDapp "n" *-- "0" DappHub

@enduml