@startuml


:Uw:

:Dw:
cloud {
  [Ds]
}
component [Ds]
component [Dp]

:Sw:
cloud {
  [Ss]
}

component [Ss]
component [Sp]

:Ww:
component [Wp]

cloud {
  [POCOs]
}
component [POCOs]




Uw -> [Ds]
Dw -up-> [Ds]
Dw -down-> Dp
Sw -up-> [Ss]
Sw --> [Sp]
[Ds] <-right-> [POCOs]
[POCOs] <-right-> [Ss]
[Sp] <-> [Ss]
[Wp] <-up-> [Ss]
[Ww] -up-> [Ss]
[Ww] -> [Wp]
[Wp] <-> [Sp]

'missing link :  [Dp] <-> [Wp] . add mannualy on img because i do not succeed to layout it






















@enduml