@startuml


:DappUser:

:DappProvider:
cloud {
  [DappContract]
}
component [DappContract]
component [AppProvider]

:SchedulerProvider:
cloud {
  [WorkerPoolContract]
}

component [WorkerPoolContract]
component [Scheduler]

:WorkerProvider:
component [Worker]

cloud {
  [POCOContract]
}
component [POCOContract]




DappUser -> [DappContract]
DappProvider -up-> [DappContract]
DappProvider -down-> AppProvider
SchedulerProvider -up-> [WorkerPoolContract]
SchedulerProvider --> [Scheduler]
[DappContract] <-right-> [POCOContract]
[POCOContract] <-right-> [WorkerPoolContract]
[Scheduler] <-> [WorkerPoolContract]
[Worker] <-up-> [WorkerPoolContract]
[WorkerProvider] -up-> [WorkerPoolContract]
[WorkerProvider] -> [Worker]
[Worker] <-> [Scheduler]

'missing link :  [AppProvider] <-> [Worker] . add mannualy on img because i do not succeed to layout it






















@enduml