@startuml
DappUserWallet -> DappContract: iexecSubmit
DappContract --> POCOContract: submitTask
note over POCOContract : generate a taskId
note over POCOContract : debit Us RLC \n(dappPrice+taskPrice)
note over POCOContract : a Dw stake dapp price ratio is locked


POCOContract -> WorkerPoolContract: submitTask
note over WorkerPoolContract :TaskStatusEnum.PENDING
Scheduler --> WorkerPoolContract : acceptTask
note over WorkerPoolContract :TaskStatusEnum.ACCEPTED
note over WorkerPoolContract :a Sw stake taskPrice ratio is locked
Scheduler  --> WorkerPoolContract : callForContribution
note over WorkerPoolContract :A worker is randomly call to work
Worker  <--> AppProvider : getApp
note over Worker :the worker do the asked task on the app
Worker  --> WorkerPoolContract : contribute
note over WorkerPoolContract :a Ww stake taskPrice ratio is locked
note over WorkerPoolContract :resultHash stored (consensus vote) \n resultSaltedHash stored (needed for poco)

Scheduler --> WorkerPoolContract : revealConsensus
note over WorkerPoolContract :TaskStatusEnum.CONSENSUS_REACHED
note over WorkerPoolContract :consensus on resultHash is revealed
note over WorkerPoolContract : a limited REVEAL_PERIOD is start in the smart contract
Worker  --> WorkerPoolContract  :reveal
note over WorkerPoolContract : during the REVEAL_PERIOD, workers reveal \n(result and salt ) for the following rewards
Scheduler  <--> Worker  : getResult
note over Scheduler : Scheduler ask and retrived result on worker who has revealed a right contribution

Scheduler --> WorkerPoolContract : finalizedTask

note over WorkerPoolContract : TaskStatusEnum.FINALIZED
note over WorkerPoolContract : Take stake of bad workers for others
note over WorkerPoolContract : unlock good workers staking
note over WorkerPoolContract : unlock scheduler staking
note over WorkerPoolContract : reward good workers
note over WorkerPoolContract : reward scheduler
WorkerPoolContract --> POCOContract : finalizedTask
note over POCOContract  : pay dapp Price dapp provider
note over POCOContract  : unlock dapp provider staking

POCOContract --> DappContract : iexecSubmitCallback

@enduml