pipeline:

  test:
    image: node:16
    pull: true
    commands:
      - npm ci --production=false
      - npm run autotest fast
      - KYC=1 npm run autotest fast

  docker_token_openethereum:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: testchains/openethereum.dockerfile
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
      - CHAIN_TYPE=token
      - CHAIN_BLOCK_TIME=1
      - CHAIN_FORCE_SEALING=false
    auto_tag: true
    auto_tag_suffix: token-openethereum
    when:
      ref: [refs/tags/v*]

  docker_native_openethereum:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: testchains/openethereum.dockerfile
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
      - CHAIN_TYPE=native
      - CHAIN_BLOCK_TIME=1
      - CHAIN_FORCE_SEALING=false
    auto_tag: true
    auto_tag_suffix: native-openethereum
    when:
      ref: [refs/tags/v*]

  docker_token_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: testchains/Dockerfile_token_ganache
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    auto_tag: true
    auto_tag_suffix: token
    when:
      ref: [refs/tags/v*]

  docker_native_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: testchains/Dockerfile_native_ganache
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    auto_tag: true
    auto_tag_suffix: native
    when:
      ref: [refs/tags/v*]

  docker_token_1s_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: testchains/Dockerfile_token_ganache_1s
    auto_tag: true
    auto_tag_suffix: token-1s
    when:
      ref: [refs/tags/v*]
