FROM parity/parity:v2.3.2

USER root

RUN apt update && apt install -y curl git ca-certificates
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
RUN bash -i -c "nvm install node"

RUN mkdir /iexec-poco
COPY . /iexec-poco

RUN bash /iexec-poco/parity_20s/migrate_20s.sh

ENTRYPOINT ["/bin/parity"]
CMD ["--chain", "/iexec-poco/parity_20s/spec_20s.json", "--config", "/iexec-poco/parity_20s/authority.toml", "--force-sealing", "-d", "/iexec-poco/parity_20s/data", "--geth"]
