FROM trufflesuite/ganache-cli:latest

USER root

RUN apk add --no-cache make gcc g++ python git bash
RUN mkdir /iexec-poco
COPY . /iexec-poco
RUN mv /iexec-poco/config/config_token.json /iexec-poco/config/config.json

ARG MNEMONIC

RUN mkdir /ganachedb
RUN bash /iexec-poco/ganache/migrate.sh

ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]
CMD ["-l", "8000000", "-i", "65535", "--hardfork", "istanbul", "--db", "/ganachedb"]
