#!/bin/bash

node_modules/.bin/ganache-cli                                                             \
	-m "actual surround disorder swim upgrade devote digital misery truly verb slide final" \
	-l 8000000                                                                              \
	-h 0.0.0.0                                                                              \
	$@
