@startuml


object App
object AppHub

object Dataset
object DatasetHub

object WorkerPool
object WorkerPoolHub

object MarketPlace

object IexecHub
object WorkOrder

AppHub <|-- IexecHub
DatasetHub <|-- IexecHub
WorkerPoolHub <|-- IexecHub

MarketPlace <|-- IexecHub

WorkerPool "n" *-- "0" WorkerPoolHub
App "n" *-- "0" AppHub
Dataset "n" *-- "0" DatasetHub

WorkOrder "n" *-- "0" IexecHub


@enduml
