ScheduleProvider@startuml


:iExecCloudUser:
:DappUser:
:AppProvider:
:ScheduleProvider:
:DatasetProvider:
:ResourceProvider:


cloud {
  [MyDapp]
  [IexecAPI]
}
component [MyDapp]
component [IexecAPI]
[IexecAPI] <|-right-  [MyDapp]



DappUser -down-> [MyDapp]: use


cloud {
  [TaskRequest]
}

component [TaskRequest]

MyDapp <-down-> [TaskRequest]: owner

iExecCloudUser -down-> [TaskRequest]: owner

cloud {
  [App]
}
component [App]
component [AppRepository]


cloud {
  [Dataset]
}
component [Dataset]
component [DatasetRepository]


cloud {
  [WorkerPool]
  [Contributions]
}

component [WorkerPool]
component [Contributions]
component [iexec-scheduler]
component [ResultRepository]

component [iexec-worker]

cloud {
  [iExecHub]
  [ProvidersScoring]
  [ProvidersBalance]
}

cloud {
  [RLC Token]
}
component [ProvidersScoring]
component [iExecHub]
component [ProvidersBalance]
component [RLC Token]


[ProvidersBalance] <-right-> [RLC Token]

[ProvidersBalance] <|-left-  [iExecHub]
[ProvidersScoring] <|-right-  [iExecHub]


AppProvider -up-> [App]: owner
AppProvider -down-> AppRepository: expose

DatasetProvider -up-> [Dataset]: owner
DatasetProvider -down-> DatasetRepository: expose

ScheduleProvider -up-> [WorkerPool]: owner

[WorkerPool] -right-> [Contributions] :create
ScheduleProvider -down-> [iexec-scheduler]: control
ScheduleProvider -down-> [ResultRepository]: control and expose
ResultRepository <-left-> [iexec-scheduler]


[Dataset] <-up-> [iExecHub]
[App] <-up-> [iExecHub]

[iExecHub] <-down-> [WorkerPool]
[iExecHub] <-down-> [Contributions]
[iExecHub] <-up-> [TaskRequest]

[iexec-scheduler] <-up-> [Contributions]
[iexec-worker] <-up-> [Contributions]

[ResourceProvider] -right-> [iexec-worker]: control

[iexec-worker] <-right-> [iexec-scheduler]


[iexec-worker] <-up-> [AppRepository]

[iexec-worker] <-up-> [DatasetRepository]

'missing link :  [AppRepository] <-> [iexec-worker] . add mannualy on img because i do not succeed to layout it



@enduml
