@startuml


:iExecCloudUser:
:DappUser:
:AppProvider:
:Sw:
:DatasetProvider:
:Ww:


cloud {
  [MyDapp]
  [IexecAPI]
}
component [MyDapp]
component [IexecAPI]
[IexecAPI] <|-right-  [MyDapp]



DappUser -down-> [MyDapp]: use


cloud {
  [TaskRequest]
}

component [TaskRequest]

MyDapp <-down-> [TaskRequest]: owner

iExecCloudUser -down-> [TaskRequest]: owner

cloud {
  [App]
}
component [App]
component [AppRepository]


cloud {
  [Dataset]
}
component [Dataset]
component [DatasetRepository]


cloud {
  [Ss]
  [Contributions]
}

component [Ss]
component [Contributions]
component [Sp]
component [Sr]

component [Wp]

cloud {
  [iExecHub]
  [ProvidersScoring]
  [ProvidersBalance]
}

cloud {
  [RLC Token]
}
component [ProvidersScoring]
component [iExecHub]
component [ProvidersBalance]
component [RLC Token]


[ProvidersBalance] <-right-> [RLC Token]

[ProvidersBalance] <|-left-  [iExecHub]
[ProvidersScoring] <|-right-  [iExecHub]


AppProvider -up-> [App]: owner
AppProvider -down-> AppRepository: expose

DatasetProvider -up-> [Dataset]: owner
DatasetProvider -down-> DatasetRepository: expose

Sw -up-> [Ss]: owner

[Ss] -right-> [Contributions] :create
Sw -down-> [Sp]: control
Sw -down-> [Sr]: control and expose
Sr <-left-> [Sp]


[Dataset] <-up-> [iExecHub]
[App] <-up-> [iExecHub]

[iExecHub] <-down-> [Ss]
[iExecHub] <-down-> [Contributions]
[iExecHub] <-up-> [TaskRequest]

[Sp] <-up-> [Contributions]
[Wp] <-up-> [Contributions]

[Ww] -right-> [Wp]: control

[Wp] <-right-> [Sp]


[Wp] <-up-> [AppRepository]

[Wp] <-up-> [DatasetRepository]

'missing link :  [AppRepository] <-> [Wp] . add mannualy on img because i do not succeed to layout it



@enduml
