@startuml
:iExecCloudUser:
:iExecSmartContractUser:
:ApplicationProvider:
:DatasetProvider:
:SchedulerProvider:
:WorkerProvider:
:OrderMatcher:

cloud {
[IexecRelay]
}
component [IexecRelay]
iExecSmartContractUser -down-> [IexecRelay]: use

component [Marketplace]
[IexecRelay] -down-> [Marketplace]: broadcast userorder
iExecCloudUser -down-> [Marketplace]: broadcast userorder
ApplicationProvider -down-> [Marketplace]: broadcast apporder
DatasetProvider -down-> [Marketplace]: broadcast dataorder
SchedulerProvider -down-> [Marketplace]: broadcast poolorder
OrderMatcher -up-> [Marketplace]: read order

cloud {
[IexecPoCo1]
[IexecPoCo2]
[RLC Token]
}
component [IexecPoCo1]
component [IexecPoCo2]
component [RLC Token]
[IexecPoCo2] <-right-> [IexecPoCo1]
[IexecPoCo1] <-right-> [RLC Token]

OrderMatcher -down-> [IexecPoCo1]: push matched orders
[IexecPoCo1] -up-> [Marketplace]: notification events

[iexec-scheduler] <-up-> [IexecPoCo2]
[iexec-worker] <-up-> [IexecPoCo2]

component [AppRegistry]
component [DatasetRegistry]
component [iexec-scheduler]
component [iexec-worker]
component [ResultRepository]

ApplicationProvider -down-> AppRegistry: expose
DatasetProvider -down-> DatasetRegistry: expose
SchedulerProvider -down-> [iexec-scheduler]: control
SchedulerProvider -down-> [ResultRepository]: control and expose
ResultRepository <-right-> [iexec-scheduler]

[WorkerProvider] -right-> [iexec-worker]: control

[iexec-worker] <-right-> [iexec-scheduler]
[iexec-worker] <-up-> [AppRegistry]
[iexec-worker] <-up-> [DatasetRegistry]
@enduml