@startuml


:iExecCloudUser:


cloud {
  [KyberNetwork]
}

cloud {
  [MyDapp]
  [IexecAPI]
  [KyberProxy]
}
component [MyDapp]
component [IexecAPI]
component [KyberProxy]
[KyberProxy] <|-left-  [MyDapp]
[IexecAPI] <|-right-  [MyDapp]

KyberProxy -up-> [KyberNetwork]: send ERC20 or ETH
KyberProxy <-up- [KyberNetwork]: get RLC TOKEN

DappUser -down-> [MyDapp]: use ERC20 or ETH

cloud {
  [TaskRequest]
}

component [TaskRequest]

MyDapp <-down-> [TaskRequest]: owner

iExecCloudUser -down-> [TaskRequest]: owner





cloud {
  [iExecHub]
}

cloud {
  [RLC Token]
}
component [iExecHub]
component [RLC Token]


[iExecHub] <-right-> [RLC Token]



[iExecHub] <-up-> [TaskRequest]: only RLC Token accepted here ( can be obtain thanks to KyberProxy )



@enduml