@startuml
object IexecAPI
object MyDapp

IexecAPI <|-- MyDapp

object App
object AppHub

object Dataset
object DatasetHub

object WorkOrder
object WorkOrderHub

object WorkerPool
object WorkerPoolHub

object IexecHub

AppHub <|-- IexecHub
DatasetHub <|-- IexecHub
WorkerPoolHub <|-- IexecHub
WorkOrderHub <|-- IexecHub


WorkerPool "n" *-- "0" WorkerPoolHub
App "n" *-- "0" AppHub
Dataset "n" *-- "0" DatasetHub
WorkOrder "n" *-- "0" WorkOrderHub



MyDapp --> WorkOrder: create


@enduml
