@startuml

box "Smart contracts" #LightBlue
	participant IexecPoco1
	participant IexecPoco2
end box

box "Off chain" #TECHNOLOGY
	participant Marketplace
end box

box "iExec Core" #Bisque
	participant Scheduler
	participant Worker
end box

box "Ressources" #LightSalmon
	participant App
	participant Dataset
end box

box "Users"
	participant Requester
	participant anyone
end box

skinparam sequenceGroupBodyBackgroundColor transparent

autonumber

@enduml
