@startuml

!include workflow-ODB-0-actors.puml

box "Smart contracts" #LightBlue
	participant SMSRegistry
end box

box "Off chain infra" #Bisque
	participant SMS
end box

!include workflow-ODB-1b-publish-orders-TEE.puml

!include workflow-ODB-2c-match2finalize-nominal-tee.puml

@enduml
