#!/bin/bash
# Converts .pulm to .png files when located in uml/ directory

cd $(dirname $0)

# See https://github.com/markushedvall/node-plantuml#cli
PLANTUML=../node_modules/node-plantuml/index.js

FORMAT=png

find *.puml \
    | xargs -I {} echo {} | sed 's/.puml//g' \
    | xargs -I {} sh -c "$PLANTUML generate {}.puml --$FORMAT -o {}.$FORMAT && echo {}.$FORMAT"