@startuml

iExecCloudUser -> MyDapp

box "Smart contracts"
	participant MyDapp
	participant IexecHub
	participant TaskRequest
  participant WorkerPool
end box


autonumber 4

MyDapp --> IexecHub: createTaskRequest(app,dataset,workerpool)
activate IexecHub
note over IexecHub : check smart contract app, workerpool, dataset (optional) asked are well registered
create TaskRequest
autonumber 4
IexecHub --> TaskRequest: createTaskRequest
note over TaskRequest :TaskRequestStatusEnum.PENDING
note over IexecHub : debit RLC user
activate TaskRequest
autonumber 4

deactivate TaskRequest
IexecHub <-- TaskRequest
autonumber 4
IexecHub --> WorkerPool :receivedTask
activate WorkerPool
note over WorkerPool :ConsensusStatusEnum.PENDING
note over WorkerPool :Log event TaskReceived(taskId)
autonumber 4
IexecHub <-- WorkerPool
deactivate WorkerPool
autonumber 4



note over IexecHub :Log event TaskRequest(taskId,workerPool)
autonumber 4
MyDapp <-- IexecHub

deactivate IexecHub
WorkerPool o-> iexec_scheduler : watch TaskReceived(taskId) event

activate iexec_scheduler

iexec_scheduler -> iexec_scheduler : analyse asked task

box "Spring boot app" #LightBlue
	participant iexec_scheduler
  participant iexec_worker
end box


box "Repository" #Bisque
	participant AppRepository
    participant DatasetRepository
end box



autonumber 5
iexec_scheduler --> WorkerPool : acceptTask(taskId)
activate WorkerPool
autonumber 5

note over WorkerPool :ConsensusStatusEnum.STARTED
autonumber 5
WorkerPool --> IexecHub
activate IexecHub

autonumber 5
IexecHub --> TaskRequest
note over IexecHub :Log event TaskAccepted(taskID);
deactivate IexecHub

note over TaskRequest :TaskRequestStatusEnum.ACCEPTED

note over WorkerPool :Log event TaskAccepted(taskID);
autonumber 5


deactivate iexec_scheduler
autonumber 5
WorkerPool o-> iexec_scheduler : watch TaskAccepted(taskID,workerPool,contributions) event
deactivate WorkerPool
autonumber 6
activate iexec_scheduler
iexec_scheduler -> iexec_scheduler : randonmy choose worker

autonumber 6
iexec_scheduler  --> WorkerPool : callForContribution(taskId,worker)
activate WorkerPool
note over WorkerPool :ConsensusStatusEnum.IN_PROGRESS
note over WorkerPool :Log event CallForContribution(worker);
autonumber 6
WorkerPool --> iexec_scheduler
deactivate WorkerPool

deactivate iexec_scheduler
autonumber 6
WorkerPool o-> iexec_worker : watch CallforContribution event
activate iexec_worker
iexec_worker  <--> AppRepository : getApp
autonumber 7
autonumber 7
iexec_worker  <--> DatasetRepository : getDataset

autonumber 7
iexec_worker-> iexec_worker: execute the asked work
activate iexec_worker
autonumber 7
iexec_worker-> iexec_worker: resultHash (vote)
autonumber 7
iexec_worker-> iexec_worker: resultSigned(proof of knowledge)
autonumber 7
iexec_worker  --> WorkerPool : contribute(resultHash,resultSigned)
deactivate  iexec_worker


activate WorkerPool
note over WorkerPool :Log event Contribute(worker,resultHash(vote));
deactivate WorkerPool
autonumber 7
WorkerPool  --> iexec_worker
deactivate  iexec_worker
deactivate WorkerPool
autonumber 7
WorkerPool o-> iexec_scheduler : watch Contribute(worker,resultHash(vote)) event
activate iexec_scheduler

autonumber 8
iexec_scheduler -> iexec_scheduler: check if consensus on resultHash is reached
autonumber 8
iexec_scheduler --> WorkerPool : revealConsensus
activate WorkerPool
note over WorkerPool :ConsensusStatusEnum.REACHED
note over WorkerPool :consensus on resultHash is revealed
note over WorkerPool : a limited REVEAL_PERIOD is start in the smart contract
note over WorkerPool :Log event RevealConsensus(consensus)
autonumber 8
WorkerPool --> iexec_scheduler
deactivate iexec_scheduler
deactivate WorkerPool
autonumber 8
WorkerPool o-> iexec_worker : watch RevealConsensus event
activate iexec_worker
autonumber 9
iexec_worker  --> WorkerPool  :reveal(result)
activate WorkerPool
note over WorkerPool : during the REVEAL_PERIOD, workers reveal \n(result and salt ) for the following rewards
note over WorkerPool :Log event Reveal(worker,result);

autonumber 9
WorkerPool  --> iexec_worker
deactivate WorkerPool
deactivate iexec_worker
autonumber 9
WorkerPool o-> iexec_scheduler : watch Reveal event
activate iexec_scheduler

autonumber 10
iexec_scheduler -> iexec_scheduler : check if all workers are reveal or reveal period end
autonumber 10
iexec_scheduler  <--> iexec_worker  : getResult
note over iexec_scheduler : iexec_scheduler ask and retrived result on worker who has revealed a right contribution

autonumber 10
iexec_scheduler --> WorkerPool : finalizedTask(stdout,stderr,uri)
activate WorkerPool
autonumber 10
note over WorkerPool : ConsensusStatusEnum.FINALIZED
autonumber 10
WorkerPool --> IexecHub :finalizedTask
autonumber 10
activate IexecHub

IexecHub --> TaskRequest :setResult(stdout,stderr,uri)
activate TaskRequest
autonumber 10
note over TaskRequest : TaskRequestStatusEnum.COMPLETED
TaskRequest <--> MyDapp : taskRequestCallback
autonumber 10
TaskRequest -> IexecHub

deactivate TaskRequest
note over IexecHub : RLC reward/seize for actors
autonumber 10
IexecHub --> WorkerPool
deactivate IexecHub
autonumber 10
WorkerPool --> iexec_scheduler : finalizedTask
deactivate WorkerPool
deactivate iexec_scheduler
deactivate TaskRequest
@enduml
