@startuml

box "Off chain actors" #TECHNOLOGY
	participant "App/Owner" as App
	participant "Dataset/Owner" as Dataset
    participant Requester
	participant anyone
end box
box "Off chain marketplace" #LightSalmon
    participant Marketplace
end box

box "Smart contracts" #LightBlue
	participant IexecPoco1
	participant IexecPoco2
end box

box "Off chain workerpool" #Bisque
	participant Scheduler
	participant Worker
end box

box "Users"

end box

skinparam sequenceGroupBodyBackgroundColor transparent

autonumber

@enduml
