@startuml

== Ressources deployment ==
activate App
App -> App : Push application
App --> IexecPoco2 : Register application
deactivate App

activate Dataset
Dataset -> Dataset : Generate encryption key (Kd)
Dataset -> Dataset : Encrypt Dataset with Kd
Dataset -> Dataset : Push dataset
Dataset --> IexecPoco2 : Register dataset
group for each application
	Dataset -> App : Get application signature
	Dataset -[#red]> SMS : Authorize application to use Kd
	Dataset -> Dataset : Add application to whitelist
end
deactivate Dataset

activate Requester
Requester -> Requester : Generate encryption key (Kr)
group for each application
	Requester -[#red]> SMS: Authorize application to use Kr
end
deactivate Requester

== Brokering ==

activate App
App -> App : sign apporder
App --> Marketplace : publish apporder
deactivate App

activate Dataset
Dataset -> Dataset : sign datasetorder
Dataset --> Marketplace : publish datasetorder
deactivate Dataset

activate Scheduler
Scheduler -> Scheduler : checks availability
Scheduler -> Scheduler : sign workerpoolorder
Scheduler --> Marketplace : publish workerpoolorder
deactivate Scheduler

activate Requester
Requester -> Requester : sign requestorder
Requester --> Marketplace : publish requestorder
deactivate Requester

@enduml
