@startuml

== Ressources deployment ==
activate App
App -> App : push application
App --> IexecPoco2 : register application
deactivate App

activate Dataset
Dataset -> Dataset : generate encryption key (Kd)
Dataset -> Dataset : encrypt Dataset with Kd
Dataset -> Dataset : push dataset
Dataset --> IexecPoco2 : register dataset
Dataset -[#red]> SMS: push Kd
group for each application
	Dataset -> App : get application signature
	Dataset -> Dataset : authorize application in datasetorder
end
Dataset -> Dataset : sign datasetorder
Dataset --> Marketplace : publish datasetorder
deactivate Dataset

activate Requester
Requester -> Requester : generate encryption key (Kr)
Requester -[#red]> SMS: push Kr
deactivate Requester

== Brokering ==

activate App
App -> App : sign apporder
App --> Marketplace : publish apporder
deactivate App

activate Scheduler
Scheduler -> Scheduler : checks availability
Scheduler -> Scheduler : sign workerpoolorder
Scheduler --> Marketplace : publish workerpoolorder
deactivate Scheduler

activate Requester
Requester -> Requester : sign requestorder
Requester --> Marketplace : publish requestorder
deactivate Requester

@enduml
