name: PoCo Contracts CI

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Cache dependencies
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check storage layout
        run: npm run check-storage-layout
      - name: Test deployment
        run: npm run deploy
      - name: Test Timelock deployment
        run: npm run deploy:timelock
      - name: Run coverage
        run: npm run coverage
      - name: Run partial native tests
        run: npm run test:native
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: iExecBlockchainComputing/PoCo
      - name: Run static analysis with Slither
        uses: crytic/slither-action@v0.4.0
        with:
          target: 'contracts/tools/testing/slither/'
          solc-version: '0.8.21'
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
          fail-on: none # TODO set this to high or other
          sarif: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
