name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.2.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
