# ⚠️ THIS WORKFLOW IS THE TRUSTED PUBLISHER CONFIGURED ON NPMJS.COM, DO NOT RENAME OR DELETE THIS FILE ⚠️
name: Publish NPM Package

on:
  pull_request:
    # tags:
    #   - 'v*'

# permissions:
#   id-token: write # Required for OIDC
#   packages: write
#   contents: read
#   security-events: write # Required for uploading SARIF files

jobs:
  build-and-test:
    uses: ./.github/workflows/main.yml

  publish:
    needs: build-and-test
    permissions:
      id-token: write # Required for OIDC
      packages: write
      contents: read
    # uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Publish Step'
        run: echo "This is a test publish step."
