name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release/*'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: nick-y-ito/gha-npm-version-match@v1
      - run: npm ci
      - run: npm run build
      #- run: npm publish --provenance --access public
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
