name: Publish NPM Package

on:
  push:
      tags:
        - 'v*'

jobs:
  build-and-test:
    uses: ./.github/workflows/main.yml

  publish:
    # needs: build-and-test
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.5.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
