# ⚠️ THIS WORKFLOW IS THE TRUSTED PUBLISHER CONFIGURED ON NPMJS.COM, DO NOT RENAME OR DELETE THIS FILE ⚠️
name: '!! Publish NPM Package --- TEST ---'

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/main.yml

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Publish Step 2'
        run: echo "This is a test publish step 2."
