# ⚠️ THIS WORKFLOW IS THE TRUSTED PUBLISHER CONFIGURED ON NPMJS.COM, DO NOT RENAME OR DELETE THIS FILE ⚠️
name: Test to debug CI

on:
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/main.yml

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Debug'
        run: echo "This is a test debug step."
